### ISSUE TITLE
Add Flathub badge in the readme file.

### ISSUE THREAD

**Issue by abuhuraira0099** [yucefsourani/albasheer-electronic-quran-browser#7]
Under the Linux installation section, you can add a 'Download on Flathub' badge containing the Flathub repo link. 

The badge can be embedded like this

```
<a href="https://flathub.org/apps/details/com.github.yucefsourani.albasheer-electronic-quran-browser" align="center">
  <img width="200" src="https://flathub.org/assets/badges/flathub-badge-i-en.png">
</a>
```

Showing the following result :
<a href="https://flathub.org/apps/details/com.github.yucefsourani.albasheer-electronic-quran-browser" align="center">
  <img width="200" src="https://flathub.org/assets/badges/flathub-badge-i-en.png">
</a>

Clicking on the badge will take you to the download page.

**Comment by yucefsourani** [comment]
thanks you .

**Comment by yucefsourani** [comment]
Done.
